name: Generic bug
description: Create a report to help us improve
title: "[Generic bug]: Insert Title Here"
labels: "Generic bug"
assignees: terminator_97
body:
  - type: markdown
    attributes:
      value: "# Thanks for taking the time to fill out this bug-report!"
  - type: textarea
    id: description
    attributes:
      label: Describe your bug
      description: Write clearly and simply what happens.
      placeholder: Write here.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: SCPUtils Version
      description: SCPUtils version
      placeholder: ie. 6.0.0
    validations:
      required: true
